name: Линтинг клиент-серверного приложения
on: 
  push: 
    branches: [ master ]
  pull_request: 
    branches: [ dev, master]
jobs:
  server: 
    name: Сервер
    runs-on: ubuntu-latest
    steps:
      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Установка модулей серверной части
        run: cd server/ && npm ci
      - name: Проверка линта
        run: npm run lint
  client:
    name: Клиент
    runs-on: ubuntu-latest
    steps:
      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Установка модулей клиентской части
        run: cd server/ && npm ci
      - name: Сборка
        run: npm run build
      - name: Проверка линта
        run: npm run lint
